services:

  reverse-proxy:
    volumes: 
      - ./traefik-config/prod/:/etc/traefik/
      - ../../volumes/letsencrypt:/letsencrypt
    labels:
      - traefik.http.routers.reverse-proxy.rule= Host(`traefik.jacquenet.com`)
      - traefik.http.routers.reverse-proxy.tls.certresolver=myresolver
      - traefik.http.routers.reverse-proxy-tls.tls.domains[0].main=jacquenet.com
      - traefik.http.routers.reverse-proxy-tls.tls.domains[0].sans=*.jacquenet.com
  
  prometheus:
    labels:
      - traefik.http.routers.prometheus.rule= Host(`jacquenet.com`) && PathPrefix(`/prometheus`)
      - traefik.http.routers.prometheus.tls.certresolver=myresolver
      - traefik.http.routers.prometheus-tls.tls.domains[0].main=jacquenet.com

  grafana:
    labels:
      - traefik.http.routers.grafana.rule= Host(`jacquenet.com`) && PathPrefix(`/grafana`)
      - traefik.http.routers.grafana.tls.certresolver=myresolver
      - traefik.http.routers.grafana-tls.tls.domains[0].main=jacquenet.com
