services:

  reverse-proxy:
    volumes: 
      - ./traefik-config/dev/:/etc/traefik/
      - ./certs/:/etc/ssl/traefik/
    labels:
        - traefik.http.routers.reverse-proxy.rule= Host(`traefik.traefik`)
        - traefik.http.routers.reverse-proxy-tls.tls.domains[0].main=traefik
        - traefik.http.routers.reverse-proxy-tls.tls.domains[0].sans=*.traefik
  
  grafana:
    labels:
        - traefik.http.routers.grafana.rule= Host(`traefik`) && PathPrefix(`/grafana`)
        - traefik.http.routers.grafana-tls.tls.domains[0].main=traefik
        - traefik.http.routers.grafana-tls.tls.domains[0].sans=traefik