version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.10
    container_name: traefik
    # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - ../../volumes/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik-config/:/etc/traefik/

    networks:
      - production-network

  prometheus :
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      # volume pour insérer le fichier de configuration de prometheus dans le container
      - ./traefik-config/prometheus.yml:/etc/prometheus/prometheus.yml
      # persister les données
      - ../../volumes/prometheus/db:/prometheus
    networks:
      - production-network
    depends_on:
      - reverse-proxy

  grafana:
    image: grafana/grafana-enterprise:10.4.2
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      # Persiste des configs, tableau de bord etc
      - ../../volumes/grafana/db:/var/lib/grafana
      # config
      - ./traefik-config/grafana.ini:/etc/grafana/grafana.ini
    labels:
      - traefik.http.routers.grafana.rule= Host(`jacquenet.com`) && PathPrefix(`/grafana`))
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=myresolver
    networks:
      - production-network
    depends_on:
      - prometheus


networks:
  production-network:
    name: production-network
    external: true