# my global config
global:
  scrape_interval: 5s
  evaluation_interval: 5s
  body_size_limit: 50MB
  sample_limit: 1500
  target_limit: 30
  label_limit: 30
  label_name_length_limit: 200
  label_value_length_limit: 200
  # scrape_timeout is set to the global default (10s).

  external_labels:
    monitor: codelab

# rule_files:
#   - "first.rules"
#   - "my/*.rules"


scrape_configs:
  - job_name: 'node'
    static_configs:
    - targets: ['jacquenet.com']
    metrics_path: '/metrics'
    scheme: 'http'
    # basic_auth:
    #   username: 'admin'
    #   password: 'pass'

   