entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  metrics:
    address: :8082


certificatesResolvers:
  myresolver:
    acme:
      email: ad.jacquenet@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web


api:
  dashboard : true
  insecure: true

providers:
  docker:
    endpoint: unix:///var/run/docker.sock   # Listen to the UNIX Docker socket
    network: production-network           # Default network to use for connections to all containers.
   
accessLog: {}

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addRoutersLabels: true
    entryPoint: prometheus