services:
  mariadb:
    image : mariadb:10.11.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PWD_MARIADB:?error}
      # WARNING #
      # Il faut se connecter avec le nom du container dans adminer dans host #
    ports:
      - "3306:3306"  # Port MariaDB
    volumes:
      - ../../volumes/mariadb/db:/var/lib/mysql:Z
      - ../../volumes/mariadb/init:/docker-entrypoint-initdb.d
      - ../../volumes/mariadb/backup:/backup
    networks:
      - production-network
  
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - production-network
    # labels:
      # - traefik.http.routers.adminer.rule=PathPrefix(`/adminer`)
    labels:
      - traefik.http.routers.adminer.tls=true


networks:
  production-network:
    name: production-network
    external: true

