version: '3'

services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PWD_MARIADB:?error}
      # XARNING #
      # Il faut se connecter avec le nom du container dans adminer dans host #
    ports:
      - "3306:3306"  # Port MariaDB
    networks:
      - production-network
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - production-network
    labels:
      - traefik.http.routers.adminer.rule=PathPrefix(`/adminer`)


networks:
  production-network:
    name: production-network
    external: true

