name: ARM_Starter CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

  
jobs:
  build:
    extends:
      - .github/workflows/build.yml

  tests:
    extends:
      - .github/workflows/tests.yml

  deploy:
    extends:
      - .github/workflows/deploy.yml

