name: ARM_Starter CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

  
jobs:
  # build:
  #   runs-on: ubuntu-latest
    
  #   environment: my-env
  #   env:
  #     ARM_VPS1_API_KEY: ${{ secrets.ARM_VPS1_API_KEY }}
  #     PWD_MARIADB: ${{ secrets.PWD_MARIADB }}
  #     PWD_MONGODB: ${{ secrets.PWD_MONGODB }}
  #     SERVER_VPS1_IP: ${{ secrets.SERVER_VPS1_IP }}
  #     USER_MARIADB: ${{ secrets.USER_MARIADB }}
  #     USER_MONGODB: ${{ secrets.USER_MONGODB }}


  #   steps:
  #     - name: Checkout main repository
  #       uses: actions/checkout@v4

  #     - name: Run containers
  #       run: bash run/run_build.sh

  # tests:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   environment: my-env
  #   env:
  #     ARM_VPS1_API_KEY: ${{ secrets.ARM_VPS1_API_KEY }}
  #     PWD_MARIADB: ${{ secrets.PWD_MARIADB }}
  #     PWD_MONGODB: ${{ secrets.PWD_MONGODB }}
  #     SERVER_VPS1_IP: ${{ secrets.SERVER_VPS1_IP }}
  #     USER_MARIADB: ${{ secrets.USER_MARIADB }}
  #     USER_MONGODB: ${{ secrets.USER_MONGODB }}

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4


  #   - name: init test plateform
  #     run: bash run/run_tests.sh

  #   - name: Run tests
  #     run: |
  #       docker exec tests pytest


  deploy:
    # needs: tests
    runs-on: ubuntu-latest

    environment: my-env
    env:
      ARM_VPS1_API_KEY: ${{ secrets.ARM_VPS1_API_KEY }}
      PWD_MARIADB: ${{ secrets.PWD_MARIADB }}
      PWD_MONGODB: ${{ secrets.PWD_MONGODB }}
      SERVER_VPS1_IP: ${{ secrets.SERVER_VPS1_IP }}
      USER_MARIADB: ${{ secrets.USER_MARIADB }}
      USER_MONGODB: ${{ secrets.USER_MONGODB }}
      SSH_PRIVATE_KEY_VPS1: ${{ secrets.SSH_PRIVATE_KEY_VPS1 }}
      SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: private key copy
      run: mkdir .ssh && echo "$SSH_PRIVATE_KEY_VPS1" > ./.ssh/id_arm

    - name: création de l'agent pour ne pas entrer la passphrase 1/2
      run: |
        sudo chmod 600 ./.ssh/id_arm 
        eval `ssh-agent`
        ssh-add ./.ssh/id_arm -o "&SSH_PASSPHRASE"

    # - name: création de l'agent pour ne pas entrer la passphrase 1/2
    #   run: printenv

    # - name: création de l'agent pour ne pas entrer la passphrase 2/2
    #   run: ssh-add ./.ssh/id_arm

    - name: rm all active container
      run: ssh debian@$SERVER_VPS1_IP "docker rm -f $(docker ps -a -q)"

    - name: Copy mariadb files
      run: scp -r ./ARM_Starter/Mariadb debian@$SERVER_VPS1_IP:/home/debian/ARMarket/ARM_Starter/Mariadb/

    - name: Copy mongodb files
      run: scp -r ./ARM_Starter/Mongodb debian@$SERVER_VPS1_IP:/home/debian/ARMarket/ARM_Starter/Mongodb/

    - name: Copy traefik files
      run: scp -r ./ARM_Starter/Traefik debian@$SERVER_VPS1_IP:/home/debian/ARMarket/ARM_Starter/Traefik/

    - name: Copy autorun file
      run: scp ./ARM_Starter/run/run_build.sh debian@$SERVER_VPS1_IP:/home/debian/ARMarket/ARM_Starter/run_build.sh

    - name: run containers
      run: scp ./ARM_Starter/run/run_build.sh debian@$SERVER_VPS1_IP:/home/debian/ARMarket/ARM_Starter/run_build.sh

    - name: rm all active container
      run: ssh debian@$SERVER_VPS1_IP "bash ./ARMarket/ARM_Starter/run_build.sh"

